---
- name: set up environments variables
  copy:
    src: files/secrets.sh
    dest: ~/secrets.sh
    mode: 0755
    group: ubuntu
    owner: ubuntu

- name: load secret
  shell: su -c 'sh ~/secrets.sh'

- name: "install nodejs"
  apt:
    name:
      - nodejs
      - npm

- name: install pm2
  shell: |
    npm install pm2 -g
    echo $TYPEORM_ENTITIES
