---
- name: set up environments variables
  script: files/secrets.sh
  # shell: |
  #   cat files/secrets.txt >> ~/.bashrc
  #   source ~/.bashrc

- name: "install nodejs"
  apt:
    name: 
      - nodejs
      - npm

- name: install pm2
  shell: npm install pm2 -g